#!/usr/bin/env python3
"""Audit Tenacious-Bench v0.1 task inventory for the four gap families claimed in memo.md.

The memo states that v0.1 had NO task coverage for:
  1. Thread-level coherence (multi-turn prior_thread with ≥2 turns)
  2. Pricing scope violations (TCV / quote band vs pricing_sheet)
  3. LinkedIn-roast / reputational tone tasks
  4. Private referral / champion context tasks

This script verifies those claims against the actual v0.1 task files and writes a
plain-text audit report to ablations/v01_coverage_audit.txt.

Usage:
    uv run python scripts/audit_v01_coverage.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
V01 = ROOT / "tenacious_bench_v0.1"
OUT = ROOT / "ablations" / "v01_coverage_audit.txt"

PARTITIONS = ["train", "dev", "held_out"]

# Keywords that would indicate coverage for each gap family
GAP_PATTERNS = {
    "thread_coherence": {
        "description": "Multi-turn tasks: prior_thread with >= 2 turns (not just one prospect message)",
        "check": "prior_thread_multi_turn",
    },
    "pricing_scope": {
        "description": "Tasks where pass/fail hinges on TCV, quote band, or pricing_sheet.md values",
        "keywords": ["tcv", "pricing_sheet", "quote band", "quote_band", "total contract", "price range", "pricing range"],
    },
    "linkedin_roast": {
        "description": "Tasks probing reputational tone: 'would this get screenshotted as bad outreach'",
        "keywords": ["linkedin", "reputation", "screenshotted", "cringe", "tone_roast", "linkedin_roast", "social_risk"],
    },
    "private_context": {
        "description": "Tasks where correct motion depends on non-public relationship facts (champion, warm intro, dormant ally)",
        "keywords": ["champion", "warm intro", "warm_intro", "private_context", "referral", "internal blocker", "named ally", "dormant"],
    },
}


def load_v01_tasks() -> list[dict]:
    tasks = []
    for partition in PARTITIONS:
        path = V01 / partition / "tasks.jsonl"
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                t = json.loads(line)
                t["_partition"] = partition
                tasks.append(t)
    return tasks


def task_blob(task: dict) -> str:
    """Flatten task to a single lowercase string for keyword search."""
    return json.dumps(task).lower()


def check_thread_coherence(tasks: list[dict]) -> list[dict]:
    """Multi-turn = prior_thread has at least 2 messages."""
    return [t for t in tasks if isinstance(t.get("input", {}).get("prior_thread"), list) and len(t["input"]["prior_thread"]) >= 2]


def check_keywords(tasks: list[dict], keywords: list[str]) -> list[dict]:
    return [t for t in tasks if any(kw in task_blob(t) for kw in keywords)]


def main() -> None:
    tasks = load_v01_tasks()
    total = len(tasks)

    # Partition breakdown
    by_partition = {}
    for p in PARTITIONS:
        by_partition[p] = sum(1 for t in tasks if t["_partition"] == p)

    # Failure category breakdown
    cat_counts: dict[str, int] = {}
    for t in tasks:
        cat = t.get("metadata", {}).get("failure_category") or t.get("failure_category") or "unknown"
        cat_counts[cat] = cat_counts.get(cat, 0) + 1

    # Gap family checks
    gap_results: dict[str, list[dict]] = {}
    gap_results["thread_coherence"] = check_thread_coherence(tasks)
    for gap, meta in GAP_PATTERNS.items():
        if gap == "thread_coherence":
            continue
        gap_results[gap] = check_keywords(tasks, meta["keywords"])

    lines = [
        "Tenacious-Bench v0.1 Coverage Audit",
        "====================================",
        "Generated by: scripts/audit_v01_coverage.py",
        f"v0.1 path: {V01}",
        "",
        f"Total tasks: {total}",
        "Partition breakdown:",
    ]
    for p, n in by_partition.items():
        lines.append(f"  {p}: {n}")

    lines += [
        "",
        "Failure category breakdown (from metadata.failure_category):",
    ]
    for cat, n in sorted(cat_counts.items(), key=lambda x: -x[1]):
        lines.append(f"  {cat}: {n}")

    lines += [
        "",
        "Gap Family Coverage Audit",
        "-------------------------",
        "The memo claims v0.1 had NO dedicated task family for four gap types.",
        "Results:",
        "",
    ]

    memo_claims_verified = True
    for gap, meta_info in GAP_PATTERNS.items():
        matched = gap_results[gap]
        description = meta_info["description"]
        if matched:
            verdict = f"PARTIAL COVERAGE ({len(matched)} tasks match)"
            memo_claims_verified = False
        else:
            verdict = "NO COVERAGE (memo claim verified)"
        lines.append(f"Gap: {gap}")
        lines.append(f"  Description: {description}")
        lines.append(f"  Verdict: {verdict}")
        if matched:
            for t in matched[:3]:
                lines.append(f"    - {t['task_id']} ({t['_partition']}): {t.get('metadata', {}).get('notes', '')}")
        lines.append("")

    lines += [
        "Summary",
        "-------",
    ]
    if memo_claims_verified:
        lines.append(
            "All four gap-family claims in memo.md are VERIFIED: v0.1 has no dedicated task family for thread_coherence (multi-turn ≥2), pricing_scope (TCV/quote), linkedin_roast, or private_context."
        )
    else:
        lines.append(
            "WARNING: One or more gap-family claims in memo.md may need updating — see "
            "PARTIAL COVERAGE verdicts above. Revise memo.md to say 'no dedicated task family' "
            "rather than 'no task coverage' if any partial matches exist."
        )

    lines += [
        "",
        "Note on thread_coherence:",
        "  v0.1 tasks may have prior_thread with 1 message (single prospect turn). The rubric",
        "  gap is about MULTI-turn threads (≥2 turns testing cross-turn consistency). Single-turn",
        "  prior_thread entries are not the same as a thread-coherence task family.",
        "",
        "Note on failure_category field:",
        "  v0.1 tasks use failure_category in metadata for the six Week 10 failure modes.",
        "  The four gap families above are ADDITIONAL task families beyond those six modes;",
        "  they would require new task_type values and rubric dimensions not present in v0.1.",
    ]

    report = "\n".join(lines)
    OUT.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nReport written to: {OUT}")


if __name__ == "__main__":
    main()
